# Generated by Django 4.0.3 on 2022-03-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='annotations',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='pictures',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='pictures',
            name='location',
            field=models.CharField(default='', max_length=200),
        ),
    ]
