# Generated by Django 4.0.3 on 2022-03-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_pictures_annotations_pictures_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pictures',
            name='name_picture',
            field=models.CharField(default='', max_length=200),
        ),
    ]
