# Generated by Django 3.1.1 on 2022-04-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_auto_20220411_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='icon',
        ),
        migrations.AlterField(
            model_name='pictures',
            name='annotations',
            field=models.CharField(default='', max_length=40),
        ),
    ]
