# Generated by Django 3.1.1 on 2022-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_auto_20220412_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictures',
            name='annotations',
            field=models.CharField(default='', max_length=50),
        ),
    ]
