# Generated by Django 4.0.3 on 2022-03-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biographies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('bio', models.TextField()),
                ('annotation', models.TextField()),
                ('career', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=10)),
                ('birth', models.CharField(max_length=50)),
                ('death', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=5)),
                ('family', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='artists/')),
            ],
        ),
    ]
