# Generated by Django 3.1.1 on 2022-04-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographies',
            name='annotation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='biographies',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
