# Generated by Django 3.1.1 on 2022-04-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20220411_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographies',
            name='annotation',
            field=models.CharField(max_length=200),
        ),
    ]
