# Generated by Django 4.0.3 on 2022-04-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_biographies_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biographies',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
